Repository ManevilleF/hexx, pull requests merged in 2023-02, with the labels that each got.

#24 Fixes ring offset
  CHANGELOG.md
  src/hex.rs
Labels: bug

#26 Iterator tools
  CHANGELOG.md
  src/hex/convert.rs
  src/hex/impls.rs
  src/hex/mod.rs
  src/hex/tests.rs
Labels: enhancement

#30 Improved rotation
  CHANGELOG.md
  src/hex/mod.rs
  src/hex/tests.rs
Labels: enhancement

#34 Hex Bounds
  CHANGELOG.md
  README.md
  src/bounds.rs
  src/hex/impls.rs
  src/hex/iter.rs
  src/hex/mod.rs
  src/hex_map.rs
  src/lib.rs
Labels: enhancement

#37 Documentation improvements
  CHANGELOG.md
  README.md
  src/direction/diagonal_direction.rs
  src/direction/hex_direction.rs
  src/hex/mod.rs
  src/layout.rs
  src/lib.rs
  src/orientation.rs
Labels: documentation

#38 Feat/extra operations
  CHANGELOG.md
  src/hex/impls.rs
  src/hex/mod.rs
  src/hex/tests.rs
Labels: bug, enhancement

#42 Pub use conversions
  src/lib.rs
Labels: bug
