Repository ManevilleF/hexx, pull requests merged in 2023-06, with the labels that each got.

#92 Directions from angle
  CHANGELOG.md
  README.md
  src/direction/diagonal_direction.rs
  src/direction/hex_direction.rs
  src/direction/mod.rs
  src/direction/tests.rs
  src/lib.rs
  src/orientation.rs
Labels: enhancement, usability

#93 Mesh builders UV options
  CHANGELOG.md
  Cargo.toml
  assets/uv_checker.png
  docs/mesh_builder.png
  examples/mesh_builder.rs
  src/mesh/column_builder.rs
  src/mesh/mod.rs
  src/mesh/plane_builder.rs
  src/mesh/uv_mapping.rs
Labels: enhancement, usability

#99 Mesh feature gate
  .github/workflows/rust.yml
  CHANGELOG.md
  Cargo.toml
  examples/mesh_builder.rs
  src/bounds.rs
  src/conversions.rs
  src/direction/diagonal_direction.rs
  src/direction/hex_direction.rs
  src/hex_map.rs
  src/layout.rs
  src/lib.rs
  src/mesh/mod.rs
  src/mesh/uv_mapping.rs
  src/orientation.rs
Labels: documentation, usability

#101 Fix for serde features
  .github/workflows/rust.yml
  CHANGELOG.md
  Cargo.toml
  README.md
  src/hex/mod.rs
Labels: bug

#100 add `bevy_reflect` feature + fix `serde` feature use in hex module
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/mesh_builder.rs
  src/bounds.rs
  src/direction/diagonal_direction.rs
  src/direction/hex_direction.rs
  src/hex/mod.rs
  src/layout.rs
  src/lib.rs
  src/mesh/column_builder.rs
  src/mesh/mod.rs
  src/mesh/plane_builder.rs
  src/mesh/uv_mapping.rs
  src/orientation.rs
Labels: enhancement

#104 Hexmod and resolution system
  CHANGELOG.md
  Cargo.toml
  README.md
  docs/chunks.png
  docs/merged_columns.png
  examples/chunks.rs
  examples/merged_columns.rs
  examples/scroll_map.rs
  examples/wrap_map.rs
  src/bounds.rs
  src/conversions.rs
  src/hex/mod.rs
  src/hex/tests.rs
  src/hex_map.rs
  src/lib.rs
Labels: enhancement, breaking-change, code quality
